config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  get 'pages/contact'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'tags/:tag', to: 'profiles#index', as: :tag

  devise_for :users, skip: :registration

  resources :profiles

  root 'profiles#index'

  get '*path', to: redirect('/404')
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # change to pretty urls
	# test title.parameterize in rails console to see how it works

	# old school pretty id
	# def to_param
	# 	"#{id}-#{title.parameterize}"		
	# end
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user

	# Paperclip
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	# Impressionist
	is_impressionable

	# Tagging
	acts_as_taggable

	#search
	def self.Search(search)
		if search 
			where(["title LIKE ?", "%#{search}%"]).order("created_at DESC")
		else
			all.order("created_at DESC")
		end
	end

	extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :profiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	after_filter :prepare_unobtrusive_flash

	def after_sign_in_path_for(resource)
	  stored_location_for(resource) || rails_admin_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /profiles
  # GET /profiles.json
  def index
    if params[:tag]
      @profiles = Profile.tagged_with(params[:tag])
    else
      @profiles = Profile.Search(params[:search])
      flash[:notice] = "no results found for \'#{params[:search]}\'" if @profiles.empty?
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    impressionist(@profile)
    @profiles = Profile.all
    @similar_profiles = Profile.tagged_with(@profile.tags)
  end

  # GET /profiles/new
  def new
    @profile = current_user.profiles.build
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.profiles.build(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:title, :url, :content, :avatar, :tag_list, :facebook, :twitter, :instagram, :location, :tagline, :industry)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Custolive</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="/main.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i" rel="stylesheet">
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="se-pre-con"></div>
  	<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            Menu <i class="fa fa-bars"></i>
          </button>
          <%= link_to root_path, class: "navbar-brand", id: "navbar-logo" do %>
            Custo<span class="txt-shadow">live</span>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li class="dropdown">
              <a href="http://ablepursuit.com/business">Register</a>
            </li>
            
            <li><a href="http://ablepursuit.com/blog">Blog</a></li>
            
            <% if user_signed_in? %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i> Logout
                <% end %>              
              </li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>
    <div id="main-content"></div>
		<%= yield %>

		<!-- The content of your page would go here. -->
    <footer class="footer-distributed" id="footer">
      <div class="footer-left"> 
        <h3>Custo<span>live</span></h3>
        <p class="footer-links">
          <%= link_to "Home", root_path %>
          ·
          <a href="http://ablepursuit.com/business">Advertise with Us</a>
          ·
          <a href="http://ablepursuit.com/blog">Blog</a>
        </p>
        <p class="footer-company-name">Powered by AblePursuit &copy; 2017</p>
      </div>

      <div class="footer-center">
        <div>
          <i class="fa fa-map-marker"></i>
          <p>East Africa</p>
        </div>
        <div>
          <i class="fa fa-whatsapp"></i>
          <p>
            <span>+254 734 530 231</span>
            <span>+254 777 530 231</span>
          </p>
        </div>
        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="mailto:hello@ablepursuit.com">hello@ablepursuit.com</a></p>
        </div>
      </div>

      <div class="footer-right">
        <p class="footer-company-about">
          <span>About AblePursuit</span>
          AblePursuit activates businesses in Africa by creating customized interpersonal relations & product experiences.<br/>
          <strong>Industry:</strong> Communication & Information Technology
        </p>
        <div class="footer-icons">
          <a href="https://www.facebook.com/ablepursuit" target="blank"><i class="fa fa-facebook"></i></a>
          <a href="https://twitter.com/ablepursuit" target="blank"><i class="fa fa-twitter"></i></a>
          <a href="https://www.instagram.com/ablepursuit/" target="blank"><i class="fa fa-instagram"></i></a>
          <a href="https://www.linkedin.com/company/ablepursuit-ltd." target="blank"><i class="fa fa-linkedin"></i></a>
        </div>
      </div>
    </footer>

    <div id="go-top" style="display: none;">
      <a href="#top">
        <i class="fa fa-caret-up"></i><br>
        Top
      </a>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>    
    <script src="https://rawgit.com/tuupola/jquery_lazyload/2.x/lazyload.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
        
  </body>
</html>

app/views/pages/about.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below.background: url('https://media.glassdoor.com/home/hero.jpg'); -->
<header class="about-header lazyload" style="background-image: url('/images/placeholder/about.jpg" data-src="/images/about-min.jpg">
  <div class="container">
    <div class="row">
      <div>
        <div class="thumbnail">
          <div class="caption">
            <h3>About us</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>


<!-- Main container -->
<div class="container" style="margin-top: 20px;">
  <div class="row">
    <div class="mbr-article mbr-article--wysiwyg col-sm-8 col-sm-offset-2">
      <p>Custolive has continued the mission to achieve the vision of being a one-of-a-kind reach for customers and the general public worldwide. AblePursuit coordinates a network of communities and develops creative solutions that provide access to information (profiles, values, databases, commentary, trends & forecasts), data enrichment, and data analytics.&nbsp;</p>
      <blockquote>
        <em>
          <b>Industry:</b> Communication Technology <br>
          <b>Target:</b> Promoting all-inclusive businesses, which are economic, social & eco-friendly. <br>
          <b>Motivation:</b> the Sustainable Development Goals&nbsp; <br>
        </em>
      </blockquote>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <figure class="mbr-figure mbr-figure--wysiwyg mbr-figure--full-width mbr-figure--caption-inside-bottom">

        <div><img class="mbr-figure__img" src="http://ablepursuit.com/wp-content/uploads/2017/03/ablepursuit.com-i17.png"></div>
        <figcaption class="mbr-figure__caption">
          <small class="mbr-figure__caption-small">What are the Sustainable Development global goals? How can businesses &amp; personalities take part? </small>
        </figcaption>
      </figure>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 entry-content">
      <p><strong>Goal 1: No Poverty</strong>
        <br> End poverty in all its forms everywhere. Access to basic services. Social inclusion of people in all locations, nations &amp; regions. Public participation of people in decision-making. Collective &amp; comprehensive approach towards ending poverty, in relation to all political, economic &amp; social aspects.
        <br>
        <em>You should be your family’s &amp; friend’s keeper by sharing &amp; investing in what you can.</em>
      </p>
      <p><strong>Goal 2: Zero Hunger</strong>
        <br> Achieve food security and improved nutrition through climate-smart agriculture, fisheries &amp; forestry. Promote growth of diversified crops like cassava, pulses, wheat, vegetables &amp; root crops to alternate shortage of others like maize. Recover lost production of industrial crops like coffee, tea, cotton, cocoa, sorghum, barley, kenaff &amp; flowers. Ensure &amp; preserve growth of fruits suitable for different topographic conditions. Promote livestock keeping, fisheries and apiaries (bees) to supply by-products that increase nutrition. Every farmer should properly utilize land, water, energy and the products to maximize supply to the market. Every one who processes/sells farm products should do so in a manner to reduce waste of food. All in all, ensure that all these practices reduce carbon emissions.
        <br>
        <em>You should produce food, whether in a container, on air or on land, doesn’t matter the size.</em>
      </p>
      <p><strong>Goal 3: Good health &amp; well-being</strong>
        <br> Continue reducing maternal mortality (50% reduction so far). Continue providing antenatal care. Continue providing vaccination against measles, polio &amp; others. Continue promoting acceptable family planning methods. Continue reducing HIV/AIDS infections and developing treatment for the infected. Continue improving right treatment for fever, asthma, diabetes, tuberculosis, pneumonia, malaria, cancer and heart related diseases. Continue saving money to access better healthcare through insurance.
        <br>
        <em>You should maintain good personal care, hygiene, behavior and lifestyle to overcome stressful conditions related to global changes.</em>
      </p>
      <p><strong>Goal 4: Quality education</strong>
        <br> Improve aid for education to war-torn countries and the developing world. Redefine equality so every one has the freedom to pursue learning with a sense of purpose. Move towards personalizing local-to-global education, so every one can learn. Improve the mindset of every learner on the purpose for education. Contextualize learning from a local-to-global perspective, based on current trends. Utilize technology as a tool for continuous learning; less examinations, more personal-to-social development. Promote teachers as facilitators and mentors of formative learning. Abolish summative assessments. Create content that informs about local issues surrounding politics, economics, society, technology, environment, and legal in relation to the global context.
        <br>
        <em>You should take liberty to teach and learn something new, at least once a day.</em>
      </p>
      <p><strong>Goal 5: Gender Equality</strong>
        <br> Close gender gap at workplaces to increase global economy by at least $5.8 trillion. Ensure equal access of women and men to basic commodities and services. Address gender disparities in countries with unfavorable cultures and violence against women. Motivate women and girls to participate in community development projects, from local-to-global perspectives. Empower women and girls in their initiatives to promote development. Contextualize sectors believed to belong to men, to suit women too.
        <br>
        <em>You should play equal roles as brothers and sisters, mothers and fathers in the house and beyond.</em>
      </p>
      <p><strong>Goal 6: Clean water &amp; Sanitation</strong>
        <br> Reserve and increase water sources and access to more households. Conserve river water basins and swampy areas by avoiding farming activities &amp; instead planting indigenous trees round them. Utilize efficient irrigation methods, instead of rainfall. Construct dams, tanks &amp; aquifers to harvest more rain water. Develop better ways to curb soil-erosion. Divert water to alternative sources in case of overflow during heavy downpour. Prevent pollution of water sources. Innovate ways to filter &amp; rid off germs and fluoride to prevent all sorts of water-borne diseases and conditions like arthritis. Build and maintain communal latrines or toilets in all densely populated areas. Conserve and utilize dams as renewable sources of energy, in addition to solar and wind. Reduce the amount of water usage in households and recycle what you can into good use.
        <br>
        <em>You should prevent wasting tap water as much as possible but always filter or boil water to drink.</em>
      </p>
      <p><strong>Goal 7: Affordable &amp; Clean energy</strong>
        <br> Promote innovation of better tools for lighting, heating and charging that are dependent on renewable (solar, wind, water) and bio-energy (waste from food &amp; animals). Removing taxation on such initiatives.
        <br>
        <em>You should know that renewable energy (solar, wind, water) is the cheapest source of energy.</em>
      </p>
      <p><strong>Goal 8: Decent work &amp; Economic growth</strong>
        <br> Create enablers for organizational development. Revise the education curriculum to meet current and future industry needs. Reduce entry level requirements for farming and technical jobs. Develop industry, infrastructure and innovation hubs in all parts of the country and continent. Connect all regions to electricity, water, sanitation, broadband, internet and forestry services to create conducive environments for investment. Encourage and support entrepreneurs to start, pilot, and expand their businesses so they can move to other regions and increase employment. Motivate employers to reward and recognize employees at all levels within the organizations. Continue easing ways of doing business. Provide ways for scalable innovations to suit political, economic, social, environmental, technical and legal factors.
        <br>
        <em>You should think long-term but focus on one idea at a time to generate income.</em>
      </p>
      <p><strong>Goal 9: Industry, Innovation and Infrastructure</strong>
        <br> Promote all-inclusive and sustainable industrial development. Promote technology as a tool, not as a mean, for industry development. Link industry to education, information and markets. Set up basic infrastructure like roads, information &amp; communication technology, water, sanitation, electricity in developing countries. Provide ways for scalable innovations to suit political, economic, social, environmental, technical and legal factors.
        <br>
        <em>You should work with industry to make innovation and infrastructure a possible reality.</em>
      </p>
      <p><strong>Goal 10: Reduced inequalities</strong>
        <br> Distribute funding fairly among regions and countries, depending on the income (GDP) level and population. Encourage youth and urban dwellers to invest back in rural homes. Encourage those living in the diaspora to invest in their home countries. Continue promoting devolution, as the greatest way to reduce inequalities. Prevent corruption by leaders at all levels. Promote each county, country, region, and continent uniquely.
        <br>
        <em>You should never underestimate the less fortunate. We are all equal before the Creator.</em>
      </p>
      <p><strong>Goal 11: Sustainable cities &amp; communities</strong>
        <br> Continue improving access to health, sanitation, water, food, security and infrastructure in urban centers. Create a city in every county. Improve cities as innovation hubs for education, art, transport, commerce, culture, science, and social development. Increase adequate housing, markets, hospitals, schools and religious centers. Control pollution, set up sewerage systems, recycle waste, utilize clean energy, rehabilitate water sources, and develop forest parks for environmental conservation.
        <br>
        <em>You should love, nurture and own your town, by keeping it clean and correcting all forms of crime.</em>
      </p>
      <p><strong>Goal 12: Responsible consumption and production</strong>
        <br> Ensure sustainable consumption and production patterns. Promote sustainability among both producers and consumers of fashion, food, energy, water and other household items.
        <br>
        <em>You should not buy something you don’t know what it’s made of.</em>
      </p>
      <p><strong>Goal 13: Climate Action</strong>
        <br> Talk about climate action in every sector. Instill climate action into the education curriculum and entertainment programs. Use a wide array of technological measures to reduce emissions. Standardize production to meet certification of carbon footprint reduction. Train on behavioral and lifestyle changes to reduce emissions drastically. Continue offering free courses on climate action – mitigation and adaptation methods.
        <br>
        <em>You should enroll for a free online course on climate action, learn and decide how to reduce footprints. </em>
      </p>
      <p><strong>Goal 14: Life below water</strong>
        <br> Safeguard biodiversity in water. Reduce pollution and destruction of coastal habitats. Rear fisheries and other marine biodiversity using eco-friendly formats. Utilize marine plants like hyacinth for feeding marine animals, and for producing bio-energy useful in the coastal livelihoods.
        <br>
        <em>You should know that oceans, seas, lakes, glaciers and dams provide &amp; regulate rainfall, drinking water, weather, climate, oxygen, beaches, and nutritious food.</em>
      </p>
      <p><strong>Goal 15: Life on land</strong>
        <br> Promote forestry as a catalyst for sustainable agriculture, recreation, education, health, water and industrial development for economic growth. Inform the importance of indigenous trees towards safeguarding life and reducing carbon emissions. Uphold laws and strict measures against those who destroy trees. Use and safely dispose off bio-products during farming.
        <br>
        <em>You should plant as many trees as you can and let animals, plants, insects live where they belong.</em>
      </p>
      <p><strong>Goal 16: Peace, Justice and Strong institutions</strong>
        <br> Mutually respect &amp; promote the rule of the law and development as interrelated factors to meet every one of the other goals.
        <br>
        <em>You should understand your constitution, and always share sentiments fairly and publicly to sort them fairly.</em>
      </p>
      <p><strong>Goal 17: Partnerships for the goals</strong>
        <br> Review strategies at local, national, regional and international levels among political, social and business organizations; make these strategies all-inclusive.
        <br>
        <em>You should share your ideas/innovations wisely with anyone (family, friends, colleagues, investors, government) who can help you make it happen.</em>
      </p>
      <p>&nbsp;</p>
      <p>Reference: <a href="http://www.un.org/sustainabledevelopment/sustainable-development-goals/">http://www.un.org/sustainabledevelopment/sustainable-development-goals/</a>
      </p>
      <p>&nbsp;</p>
      <p><em><strong>AblePursuit is a customer relations outfit for businesses looking for markets. </strong></em>
      </p>
      <p><em><strong>We also recommend development agencies, social institutions and government as associates, clientele or investors.<br>
      </strong></em>
      </p>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<style>
  body {
    background-color: #f1f1f1;
  }
</style>

<!-- Page Header -->
<!-- Set your background image for this header on the line below.background: url('https://media.glassdoor.com/home/hero.jpg'); -->
<header class="intro-header lazyload" style="background-image: url('/images/placeholder/intro.jpg" data-src="/images/intro-min.jpg">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1 class="txt-shadow">Custolive</h1>
            
            <%= form_tag profiles_path, :method => 'get', class: 'form-inline' do %>
              <div class="input-group">
                <%= search_field_tag :search, params[:search], type: "text", class: "form-control", size: "60", placeholder: "Business name" %>
                <span class="input-group-btn">
                  <%= submit_tag "", name: nil, class: "btn btn-default" %>
                </span>
              </div>
            <% end %>
            
          <span class="subheading">search</span>
          
        </div>
      </div>
    </div>
  </div>
</header>

<!-- container -->
<div class="container" id="my-container">
  <div class="h2-container">
    <h2>
      Creating 'business to customer' experiences on web, social media, blogs &amp; events. <br/>
    </h2>
    <h3>Powered by <a href="http://ablepursuit.com">@AblePursuit</a></h3>
  </div>  
  <div class="row">
    <% @profiles.each do |profile| %>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="my-box bg-white">
          <%= link_to profile do %>
            <%= image_tag profile.avatar.url, class: "img-responsive shadow" %>
          <% end %>
          <div class="cell-body">
            <h4><%= profile.title %></h4>
            <p><%= profile.tagline %>&nbsp;<%= link_to 'read more', profile %></p>
            <%#= link_to profile, class: 'btn btn-default' do %>
              <!--span>Read more</span-->
            <%# end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- horizantal icons -->
<section id="horizantal-icons">
  <div class="container">
    <div class="row text-center">
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="horizantal-icons-container">
          <img class="img-responsive hz-icons" src="/images/horizantal-icons/data-visualization.png"/><br/>
          <h2>Data Visualization</h2>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="horizantal-icons-container customer-experience">
          <img class="img-responsive hz-icons" src="/images/horizantal-icons/customer-xp.png"/><br/>
          <h2>Customer Experience</h2>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="horizantal-icons-container">
          <img class="img-responsive hz-icons" src="/images/horizantal-icons/product-feature.png"/><br/>
          <h2>Product Feature</h2>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/profiles/new.html.erb
<div class="container" style="padding-top: 70px;">
	<h1>New Profile</h1>

	<%= render 'form', profile: @profile %>

	<%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<!-- Page Content -->
<div class="container" style="padding-top: 115px;">
  <div class="row">
    <!-- Blog Post Content Column -->
    <div class="col-lg-8">
      
      <article class="full_post post type-post status-publish format-standard has-post-thumbnail hentry category-workspace tag-inspiration tag-workspace">
        <div class="post-header">
          <h1><%= @profile.title %></h1>
          <div class="decorater">
              <div class="line"><span class="dot"></span></div>
          </div>
          <div class="post-meta">
            <div class="meta_date"><span class="posted">Posted on </span><%= @profile.created_at.strftime("%b %d, %Y") %></div>
          </div>
        </div>
        <div class="post-img">
          <%= image_tag @profile.avatar.url, class: "attachment-swanky-full-thumb size-swanky-full-thumb wp-post-image shadow", alt: "profile image", width: "1080", height: "720" %>
          </div>
        <div class="content_post_wrap">
          <div class="post-entry">
            <p><%= @profile.tagline %></p>
      
            <p><%= @profile.content %></p>
            
            <div class="post-tags">
              <h5 class="tags">Industry :</h5>         
                <span class="tags_wrap">
                  <%= link_to @profile.industry, "#" %>
                </span>              
            </div>

            <div class="post-tags">
              <h5 class="tags">Tags :</h5>              
              <% @profile.tag_list.map do |t| %>
                <span class="tags_wrap">
                  <%= link_to t, tag_path(t) %>
                  </span>
              <% end %>
            </div>
          </div>
        </div>
        
        <div class="content_metabottom_wrap">
          <div class="meta_bottom">
            <div class="post-share">
              <% if user_signed_in? %>
                <div class="text_share">Edit profile</div>
                <%= link_to edit_profile_path do %>
                  <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        
      </article>
      

    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">
      
      <!-- Blog Search Well -->
      <div class="well" id="show-search">
        <h5 class="tags">Search</h5>
        <%= form_tag profiles_path, :method => 'get', class: 'form-inline' do %>
          <div class="input-group">
            <%= search_field_tag :search, params[:search], type: "text", class: "form-control", size: "100%", placeholder: "Company name" %>
            <span class="input-group-btn">
              <%= submit_tag "", class: "btn btn-default" %>
            </span>
          </div>
        <% end %>
      </div>

      <!-- Blog Categories Well -->
      <div class="well">
        <h5 class="tags">Social Links</h5>
        <ul class="socials">
            <li style="<%= "display: none;" unless @profile.facebook.present? %>">
                <a href="https://www.facebook.com/<%= @profile.facebook %>">
                  <i class="fa fa-facebook"></i>
                </a>
            </li>
            <li style="<%= "display: none;" unless @profile.twitter.present? %>">
                <a href="https://www.twitter.com/<%= @profile.twitter %>">
                  <i class="fa fa-twitter"></i>
                </a>
            </li>
            <li style="<%= "display: none;" unless @profile.url.present? %>">
                <a href="<%= @profile.url %>"> <i class="fa fa-link"></i> </a>
            </li>
            <li style="<%= "display: none;" unless @profile.instagram.present? %>">
                <a href="https://www.instagram.com/<%= @profile.instagram %>">
                  <i class="fa fa-instagram"></i>
                </a>
            </li>
            <li style="<%= "display: none;" unless @profile.location.present? %>">
                <a href="#" data-toggle="tooltip", data-placement="bottom" title="<%= @profile.location %>">
                  <i class="fa fa-location-arrow"></i>
                </a>
            </li>
        </ul>
      </div>

      <% unless @similar_profiles.empty? %>
        <div class="well">
          <h5 class="tags">Similar organizations</h5>
          <div class="similar-profiles">
            <% @similar_profiles.map do |similar_profile| %>
              <%= link_to similar_profile.title, similar_profile %>,
            <% end %>
          </div>
        </div>
      <% end %>
      
      <div class="well">
        <div class="post-tags" style="margin-top: 0px;">
          <h5 class="tags">Browse by category</h5>          
          <% ActsAsTaggableOn::Tag.most_used(5).each do |tagging| %>
            <span class="tags_wrap">
              <%= link_to tagging, tag_path(tagging.name) %>
            </span>
          <% end %>          
        </div>
      </div>
      
    </div>

  </div>
  <!-- /.row -->
</div>
<!-- /.container 